### ISSUE TITLE
[Feature Request] Bedrock Version

### ISSUE THREAD

**Issue by waddon1** [eccentricdevotion/TARDIS-SoundResourcePack#4]
Would it be possible to create a bedrock version of this resource pack for servers that use geyser?

**Comment by eccentricdevotion** [comment]
Yes, should be possible, I'll have a go.

**Comment by eccentricdevotion** [comment]
https://www.dropbox.com/s/saz4sgjfd6spk59/TARDIS-Sounds-Bedrock.mcpack?dl=0

Should work...
I can hear the sounds when I use the `/playsound` command in Bedrock edition, but I only have access to Education Edition for testing.

**Comment by waddon1** [comment]
Thanks I'll give it a try tomorrow

**Comment by waddon1** [comment]
I tried it out yesterday with the playsound command and with the actual plugin and both worked fine.
